# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElectiveCourses', '0002_auto_20151213_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default='Unknown', max_length=128),
        ),
    ]
